# Generated by Django 5.0.6 on 2024-06-24 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_hotel', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('price_range', models.CharField(max_length=20)),
                ('contact_of_hotel', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=50)),
                ('contact_of_user', models.CharField(max_length=50)),
                ('date_booked', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
